const test = ["
    Nyiragiciro grace",
"UKWISHAKA Odette",
Nyirantonesha Alice,
Niyigena Uwase Ruth,
Nyaziraje Soleil,
Sabato Claudette,
Nkomezi Shalon, 
Muhorakeye Eugenie,
Manishimwe Isabella,
Uwiringiyimana Grace,
Igiraneza Rachel,
Uwimuhwe Janette,
Umutoni Claudine,
Nyirashimwe Nyirasuku,
Mutimukeye joyeuse,
Ishimire Kamashara Giselle,
Nyirashimwe Nyirasuku,
Iradukunda Adeline,
Muziranenge Valeur,
Shakira MUKASHEMA,
Muziranenge Valuer,
Prince Iranzi,
ishimwe deo,
Niyonsenga Jean Claude,
Ndayiringiye David,
Ngabonziza Bienvenue,
Hakizuwera Jeapetit,
Nshizirungu Jean de Dieu, 
Habinshuti Theogene,
Niyomugenga Benoit,
Gashema Denis sAMUEL,
Munyejabo Elie,
Ndayishimiye Mpamira,
Gashema Samuel,
Mbangukira Emmanuel,
Sekaneza Innocent,
Kimararungu Pacipfique,
Ndahayo Faustin,
GITIMBWA Andre,
Muvugizi charmand,
David NIYONGIRA,
Kimararungu Alex,
Cyubahiro Honore, 
Irunva Jean,
Hategekimana Michel,
Nguweneza John,
Uwase Pacifique,
Iradukunda theophile,
Ndungutse Musafiri,
Bijanga Rwakibibi Frederrick,
Rutete Niyonzima,
Mugisha Sept,
Ndakangwa Olivier,
Nkurunziza Pacifique,
Niyibikora Justin,
Mbona Bucya Irunva,
Nshuti Kizima Cedric,
Ishimwe Cedric,
Niyongabo Theophile,
Uwineza Jean Paul,
Busoke Bonane,
Heritier Shema,
Mbonyubwabo Rugira
Nsanzabandi Neville,
Merci Bienvenue,
Gisubizo Janvier,
Niyonkuru Rene,
NSHIZIRUNGU Jean De Dieu,
niyonzima rutete,
SEBAZIGA John,
Sibobugingo Emmanuel
]